package com.bank.controller;

import com.bank.dao.LoanDAO;
import com.bank.model.Loan;
import com.itextpdf.text.Document;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet("/LoanPdfServlet")
public class LoanPdfServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response)
            throws ServletException, IOException {

        try {

            int loanId =
                    Integer.parseInt(request.getParameter("loanId"));

            LoanDAO dao = new LoanDAO();

            Loan loan = dao.getLoanById(loanId);

            if (loan == null) {

                response.getWriter().println("Loan Not Found");

                return;
            }

            response.setContentType("application/pdf");

            response.setHeader(
                    "Content-Disposition",
                    "attachment; filename=Loan_" + loanId + ".pdf");

            Document document = new Document();

            PdfWriter.getInstance(
                    document,
                    response.getOutputStream());

            document.open();

            Font title =
                    new Font(Font.FontFamily.HELVETICA, 18, Font.BOLD);

            Font heading =
                    new Font(Font.FontFamily.HELVETICA, 14, Font.BOLD);

            Font normal =
                    new Font(Font.FontFamily.HELVETICA, 12);

            document.add(new Paragraph("SK MINI BANK", title));
            document.add(new Paragraph(" "));
            document.add(new Paragraph("Loan Application Details", heading));
            document.add(new Paragraph(" "));

            document.add(new Paragraph("Loan ID : " + loan.getLoanId(), normal));
            document.add(new Paragraph("Customer ID : " + loan.getCustomerId(), normal));
            document.add(new Paragraph("Customer Name : " + loan.getCustomerName(), normal));
            document.add(new Paragraph("Account Number : " + loan.getAccountNumber(), normal));
            document.add(new Paragraph("Loan Type : " + loan.getLoanType(), normal));
            document.add(new Paragraph("Loan Amount : ₹ " + loan.getLoanAmount(), normal));
            document.add(new Paragraph("Interest Rate : " + loan.getInterestRate() + " %", normal));
            document.add(new Paragraph("Duration : " + loan.getDurationYear() + " Years", normal));
            document.add(new Paragraph("Status : " + loan.getStatus(), normal));
            document.add(new Paragraph("Apply Date : " + loan.getApplyDate(), normal));

            document.add(new Paragraph(" "));
            document.add(new Paragraph("-------------------------------------------"));
            document.add(new Paragraph("Generated By SK MINI BANK"));
            document.add(new Paragraph("Thank You"));

            document.close();

        } catch (Exception e) {

            e.printStackTrace();

            response.getWriter().println(e.getMessage());

        }

    }

}