package com.bank.controller;

import com.bank.dao.TransactionDAO;
import com.bank.model.Transaction;

import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet("/TransactionPDFServlet")
public class TransactionPDFServlet extends HttpServlet {

    @Override
    protected void doGet(HttpServletRequest request,
            HttpServletResponse response)
            throws ServletException, IOException {

        String accountNumber = request.getParameter("accountNumber");

        System.out.println("PDF Account Number : " + accountNumber);

        if (accountNumber == null || accountNumber.trim().isEmpty()) {
            response.getWriter().println("Account Number Missing");
            return;
        }

        TransactionDAO dao = new TransactionDAO();
        List<Transaction> list = dao.getTransactionsByAccount(accountNumber);

        response.setContentType("application/pdf");
        response.setHeader("Content-Disposition",
                "attachment;filename=TransactionHistory.pdf");

        try {

            Document document = new Document(PageSize.A4);
            PdfWriter.getInstance(document, response.getOutputStream());

            document.open();

            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18);
            Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 11);
            Font bodyFont = FontFactory.getFont(FontFactory.HELVETICA, 10);

            Paragraph title = new Paragraph("SK MINI BANK", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);

            Paragraph sub = new Paragraph("Transaction History", headerFont);
            sub.setAlignment(Element.ALIGN_CENTER);
            document.add(sub);

            document.add(new Paragraph(" "));

            document.add(new Paragraph("Account Number : " + accountNumber, bodyFont));
            document.add(new Paragraph("Total Transactions : " + list.size(), bodyFont));

            document.add(new Paragraph(" "));

            PdfPTable table = new PdfPTable(7);
            table.setWidthPercentage(100);

            table.setWidths(new float[]{1.2f, 3f, 2f, 2f, 2f, 3f, 2f});

            PdfPCell cell;

            cell = new PdfPCell(new Paragraph("ID", headerFont));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);

            cell = new PdfPCell(new Paragraph("Customer", headerFont));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);

            cell = new PdfPCell(new Paragraph("Type", headerFont));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);

            cell = new PdfPCell(new Paragraph("Amount", headerFont));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);

            cell = new PdfPCell(new Paragraph("Balance", headerFont));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);

            cell = new PdfPCell(new Paragraph("Date", headerFont));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);

            cell = new PdfPCell(new Paragraph("Status", headerFont));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);

            for (Transaction t : list) {

                table.addCell(new Paragraph(String.valueOf(t.getId()), bodyFont));
                table.addCell(new Paragraph(t.getCustomerName(), bodyFont));
                table.addCell(new Paragraph(t.getTransactionType(), bodyFont));
                table.addCell(new Paragraph("Rs. " + t.getAmount(), bodyFont));
                table.addCell(new Paragraph("Rs. " + t.getBalance(), bodyFont));
                table.addCell(new Paragraph(String.valueOf(t.getTransactionDate()), bodyFont));
                table.addCell(new Paragraph(t.getStatus(), bodyFont));

            }

            document.add(table);

            document.add(new Paragraph(" "));

            Paragraph footer = new Paragraph(
                    "Generated by SK Mini Bank",
                    FontFactory.getFont(FontFactory.HELVETICA_BOLD, 11));

            footer.setAlignment(Element.ALIGN_CENTER);

            document.add(footer);

            document.close();

        } catch (Exception e) {

            e.printStackTrace();

        }

    }
}