events {
    worker_connections 1024;
}

http {
    upstream auth_servers {
        server auth-service:3000;
    }

    upstream transaction_servers {
        server transaction-service:3000;
    }

    server {
        listen 80;

        # Auth Routes
        location /api/login {
            proxy_pass http://auth_servers;
        }
        location /api/sendOtp {
            proxy_pass http://auth_servers;
        }
        location /api/profile {
            proxy_pass http://auth_servers;
        }

        # Transaction Routes
        location /api/transfer {
            proxy_pass http://transaction_servers;
        }
        location /api/upi {
            proxy_pass http://transaction_servers;
        }
        location /api/transactions {
            proxy_pass http://transaction_servers;
        }

        # Default fallback
        location / {
            proxy_pass http://auth_servers;
        }
    }
}
